
#import "XMLObject.h"

@class XMLTracklist;

@interface XMLNode : XMLObject
{
    NSString *_name;
	NSString *_id;
	NSString *_url;
	NSString *_urlid;
	NSString *_sid;
	NSString *_player;
	NSString *_img;
	NSString *_desc;
	NSString *_fav;
	NSString *_author;
	NSString *_color;
	NSString *_bcolor;
	NSString *_skip;
	NSString *_info;
	NSString *_type;
	NSString *_shout;
	NSString *_title;
	NSString *_adurl;
	NSString *_icon;
	NSString *_adimg;
	NSString *_adid;
	NSString *_adpage;
	NSString *_addart;
	NSString *_adwidth;
	NSString *_adheight;
	NSString *_podcast;
	NSString *_playlist;
	NSString *_rawurl;
	NSString *_meta;
	NSString *_rotator;
	NSString *_shouturl;
	NSString *_prerollad;
	NSString *_prerollwidth;
	NSString *_prerollheight;
	NSString *_local;
	NSString *_value;
	NSString *_pid;
	NSString *_guideid;
	NSString *_align;
	NSString *_minback;
	NSString *_duration;
	NSString *_path;
	NSString *_banner;	
	NSString *_adbannerzone;
	NSString *_adbannerwidth;
	NSString *_adbannerheight;
	NSString *_adbannerfreq;
	NSString *_adprerollzone;
	NSString *_adprerollwidth;
	NSString *_adprerollheight;
	NSString *_adprerollfreq;
	NSString *_adpopupzone;
	NSString *_adpopupwidth;
	NSString *_adpopupheight;
	NSString *_adpopupfreq;
	NSString *_adinterzone;
	NSString *_adinterwidth;
	NSString *_adinterheight;
	NSString *_adinterfreq;
	NSString *_adsignupzone;
	NSString *_adsignupwidth;
	NSString *_adsignupheight;
	NSString *_adsignupfreq;		
	int _width;
	int _height;
	int _expdays;
	int _expplays;
	int _bannerfreq;
	int _interfreq;
	int _allowdelete;
	int _allowshuffle;
	int _autohide;
	int _autoshuffle;
	int _rating;
	int _adindex;
	double _timecode;
	BOOL _offline;
	BOOL _isLast;
	BOOL _isRecording;
	BOOL _isFlyBack;
	BOOL _isJumping;
	BOOL _isAudioPodcast;
	BOOL _isVideoPodcast;
	UIImage *_adart;
	XMLTracklist *_tracklist;
}

@property (nonatomic, retain) NSString *nodename;
@property (nonatomic, retain) NSString *nodeid;
@property (nonatomic, retain) NSString *nodeurl;
@property (nonatomic, retain) NSString *nodeurlid;
@property (nonatomic, retain) NSString *nodesid;
@property (nonatomic, retain) NSString *nodeplayer;
@property (nonatomic, retain) NSString *nodeimg;
@property (nonatomic, retain) NSString *nodedesc;
@property (nonatomic, retain) NSString *nodefav;
@property (nonatomic, retain) NSString *nodeauthor;
@property (nonatomic, retain) NSString *nodecolor;
@property (nonatomic, retain) NSString *nodebcolor;
@property (nonatomic, retain) NSString *nodeskip;
@property (nonatomic, retain) NSString *nodeinfo;
@property (nonatomic, retain) NSString *nodetype;
@property (nonatomic, retain) NSString *nodeshout;
@property (nonatomic, retain) NSString *nodetitle;
@property (nonatomic, retain) NSString *nodeadurl;
@property (nonatomic, retain) NSString *nodeadimg;
@property (nonatomic, retain) NSString *nodeicon;
@property (nonatomic, retain) NSString *nodeadid;
@property (nonatomic, retain) NSString *nodeadpage;
@property (nonatomic, retain) NSString *nodeaddart;
@property (nonatomic, retain) NSString *nodeadwidth;
@property (nonatomic, retain) NSString *nodeadheight;
@property (nonatomic, retain) NSString *nodepodcast;
@property (nonatomic, retain) NSString *nodeplaylist;
@property (nonatomic, retain) NSString *nodeprerollad;
@property (nonatomic, retain) NSString *nodeprerollwidth;
@property (nonatomic, retain) NSString *nodeprerollheight;
@property (nonatomic, retain) NSString *noderawurl;
@property (nonatomic, retain) NSString *nodemeta;
@property (nonatomic, retain) NSString *noderotator;
@property (nonatomic, retain) NSString *nodeshouturl;
@property (nonatomic, retain) NSString *nodelocal;
@property (nonatomic, retain) NSString *nodevalue;
@property (nonatomic, retain) NSString *nodepid;
@property (nonatomic, retain) NSString *nodeguideid;
@property (nonatomic, retain) NSString *nodealign;
@property (nonatomic, retain) NSString *nodeminback;
@property (nonatomic, retain) NSString *nodeduration;
@property (nonatomic, retain) NSString *nodepath;
@property (nonatomic, retain) NSString *nodebanner;
@property (nonatomic, retain) NSString *adbannerzone;
@property (nonatomic, retain) NSString *adbannerwidth;
@property (nonatomic, retain) NSString *adbannerheight;
@property (nonatomic, retain) NSString *adbannerfreq;
@property (nonatomic, retain) NSString *adprerollzone;
@property (nonatomic, retain) NSString *adprerollwidth;
@property (nonatomic, retain) NSString *adprerollheight;
@property (nonatomic, retain) NSString *adprerollfreq;
@property (nonatomic, retain) NSString *adpopupzone;
@property (nonatomic, retain) NSString *adpopupwidth;
@property (nonatomic, retain) NSString *adpopupheight;
@property (nonatomic, retain) NSString *adpopupfreq;
@property (nonatomic, retain) NSString *adinterzone;
@property (nonatomic, retain) NSString *adinterwidth;
@property (nonatomic, retain) NSString *adinterheight;
@property (nonatomic, retain) NSString *adinterfreq;
@property (nonatomic, retain) NSString *adsignupzone;
@property (nonatomic, retain) NSString *adsignupwidth;
@property (nonatomic, retain) NSString *adsignupheight;
@property (nonatomic, retain) NSString *adsignupfreq;
@property (nonatomic) int nodewidth;
@property (nonatomic) int nodeheight;
@property (nonatomic) int nodeexpdays;
@property (nonatomic) int nodeexpplays;
@property (nonatomic) int nodebannerfreq;
@property (nonatomic) int nodeinterfreq;
@property (nonatomic) int nodeallowdelete;
@property (nonatomic) int nodeallowshuffle;
@property (nonatomic) int nodeautohide;
@property (nonatomic) int nodeautoshuffle;
@property (nonatomic) int noderating;
@property (nonatomic) int nodeadindex;
@property (nonatomic) double nodetimecode;
@property (nonatomic) BOOL nodeoffline;
@property (nonatomic) BOOL nodeisRecording;
@property (nonatomic) BOOL nodeisFlyBack;
@property (nonatomic) BOOL nodeisJumping;
@property (nonatomic) BOOL nodeisAudioPodcast;
@property (nonatomic) BOOL nodeisVideoPodcast;
@property (nonatomic) BOOL nodeisLast;
@property (nonatomic, retain) UIImage *nodeadart;
@property (nonatomic, retain) XMLTracklist *tracklist;

@end
