
#import "XMLObject.h"

@interface XMLTracklist : XMLObject
{
	NSString *_station;
    NSString *_imageurl;
    NSString *_livemediaurl;
    NSString *_stopGuid;
    NSString *_session;
	NSString *_banner;	
	NSString *_adbannerzone;
	NSString *_adbannerwidth;
	NSString *_adbannerheight;
	NSString *_adbannerfreq;
	NSString *_adprerollzone;
	NSString *_adprerollwidth;
	NSString *_adprerollheight;
	NSString *_adprerollfreq;
	NSString *_adpopupzone;
	NSString *_adpopupwidth;
	NSString *_adpopupheight;
	NSString *_adpopupfreq;
	NSString *_adinterzone;
	NSString *_adinterwidth;
	NSString *_adinterheight;
	NSString *_adinterfreq;
	NSString *_adsignupzone;
	NSString *_adsignupwidth;
	NSString *_adsignupheight;
	NSString *_adsignupfreq;	
    int _stationid;
    int _bitrate;
    int _startindex;
    BOOL _autoplay;
    BOOL _continuing;
    BOOL _shuffleable;
    BOOL _deleteable;
    BOOL _podcasting;
    BOOL _shoutcasting;
    BOOL _flycasting;
    BOOL _flybacking;
    BOOL _recording;
    BOOL _offline;
    BOOL _cached;
    BOOL _live;
    BOOL _saved;
    BOOL _throwaway;
    BOOL _shuffled;
    BOOL _autohide;
    BOOL _autoshuffle;
    BOOL _users;
    BOOL _video;
    int _expdays;
    int _expplays;
	int _bannerfreq;
	int _interfreq;
	int _adindex;
    UIImage *_original;
    NSString *_albumfile;
    NSString *_basealbum;
    double _timecode;
}

@property (nonatomic, retain) NSString *station;
@property (nonatomic, retain) NSString *imageurl;
@property (nonatomic, retain) NSString *livemediaurl;
@property (nonatomic, retain) NSString *stopGuid;
@property (nonatomic, retain) NSString *session;
@property (nonatomic, retain) NSString *banner;
@property (nonatomic) int stationid;
@property (nonatomic) int bitrate;
@property (nonatomic) int startindex;
@property (nonatomic) BOOL autoplay;
@property (nonatomic) BOOL continuing;
@property (nonatomic) BOOL shuffleable;
@property (nonatomic) BOOL deleteable;
@property (nonatomic) BOOL podcasting;
@property (nonatomic) BOOL shoutcasting;
@property (nonatomic) BOOL flycasting;
@property (nonatomic) BOOL flybacking;
@property (nonatomic) BOOL recording;
@property (nonatomic) BOOL offline;
@property (nonatomic) BOOL cached;
@property (nonatomic) BOOL saved;
@property (nonatomic) BOOL live;
@property (nonatomic) BOOL throwaway;
@property (nonatomic) BOOL shuffled;
@property (nonatomic) BOOL autohide;
@property (nonatomic) BOOL autoshuffle;
@property (nonatomic) BOOL users;
@property (nonatomic) BOOL video;
@property (nonatomic) int expdays;
@property (nonatomic) int expplays;
@property (nonatomic) int bannerfreq;
@property (nonatomic) int interfreq;
@property (nonatomic) int adindex;
@property (nonatomic, retain) UIImage *original;
@property (nonatomic, retain) NSString *albumfile;
@property (nonatomic, retain) NSString *basealbum;
@property (nonatomic, retain) NSString *adbannerzone;
@property (nonatomic, retain) NSString *adbannerwidth;
@property (nonatomic, retain) NSString *adbannerheight;
@property (nonatomic, retain) NSString *adbannerfreq;
@property (nonatomic, retain) NSString *adprerollzone;
@property (nonatomic, retain) NSString *adprerollwidth;
@property (nonatomic, retain) NSString *adprerollheight;
@property (nonatomic, retain) NSString *adprerollfreq;
@property (nonatomic, retain) NSString *adpopupzone;
@property (nonatomic, retain) NSString *adpopupwidth;
@property (nonatomic, retain) NSString *adpopupheight;
@property (nonatomic, retain) NSString *adpopupfreq;
@property (nonatomic, retain) NSString *adinterzone;
@property (nonatomic, retain) NSString *adinterwidth;
@property (nonatomic, retain) NSString *adinterheight;
@property (nonatomic, retain) NSString *adinterfreq;
@property (nonatomic, retain) NSString *adsignupzone;
@property (nonatomic, retain) NSString *adsignupwidth;
@property (nonatomic, retain) NSString *adsignupheight;
@property (nonatomic, retain) NSString *adsignupfreq;
@property (nonatomic) double timecode;

- (void)copy:(XMLTracklist *)tracklist;

@end
